services:
  travel-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel-agent-backend
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000
    env_file:
      - path: ./backend/.env
        required: true
    entrypoint: ["/app/scripts/start-backend.dev.sh"]

  travel-frontend:
    restart: always
    container_name: travel-agent-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    command: ["npm", "run", "dev"]